<!--Footer Section-->
    <footer>
        <div class="footer-content">
            <img class="logo" src="images/logo.png" alt="logo">
            <p>Your satisfaction is our pleasure!</p>
            <p>Address: 2 Duong Khue, Mai Dich, Hanoi</p>
            <ul class="socials">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin-square"></i></a></li>
            </ul>
        </div>

    </footer>